### ISSUE TITLE
How to Use bot program

### ISSUE THREAD

**Issue by Billty09** [woody34/L2RBot#1]
Please make videos tutorial

**Comment by woody34** [comment]
here is a video on the bots operation [https://streamable.com/jsvvc](url)

I have added ['Documentation>L2RBot tutorial.docx'](https://github.com/woody34/L2RBot/blob/master/WpfApp2/Documentation/L2RBot%20tutorial.docx) as an initial setup guide

**Comment by woody34** [comment]
I'll leave it open incase you have any questions.

**Comment by Billty09** [comment]
Do I need Visual Studio first?

**Comment by woody34** [comment]
I have added a binary folder to make it easier for you to use. Visual Studio is great but has a slight learning curve if you are new to development. Please let me know how the software works for you.
[/_bin/L2R.exe](https://github.com/woody34/L2RBot/tree/master/WpfApp2/_bin)


นี่คือโฟลเดอร์ที่มีปฏิบัติการไบนารี 
นี้เป็นเรื่องง่ายกว่าการดาวน์โหลดและการเรียนรู้ IDE
โปรดแจ้งให้เราทราบหากคุณมีปัญหา<--rough Thai translation
[/_bin/L2R.exe](https://github.com/woody34/L2RBot/tree/master/WpfApp2/_bin)

**Comment by Billty09** [comment]
Don't work 
![dontwork](https://user-images.githubusercontent.com/21139805/31676509-0e889d56-b392-11e7-9ab0-1910939ba3e2.jpg)

My nox 
![dontwork2](https://user-images.githubusercontent.com/21139805/31676574-431233ac-b392-11e7-874c-99068aa576e8.jpg)

**Comment by woody34** [comment]
Your NoxPlayer resolution has been changed when you resized the window. I can tell based on how much smaller the game screen is than the settings screen. See the screenshot I attached and look at how much bigger the game window is than the settings window.

![screenshot 518](https://user-images.githubusercontent.com/8930703/31694000-446dbcd8-b367-11e7-8e3f-c9604290ba8c.png)

You need to change NoxPlayer to 1280x720 again. It was set to the right size then you resized the window which is why it is not working but still appears to be set correctly

You can do so by changing it to 1920x1080 and save(you do not have to restart.) then change it back to 1280x720 and save(restart this time.) After this do not resize the window again or you will have to repeat this process. 

I don't think the Darkdaddy bot is supported anymore. last i checked he hasn't pushed out any updates. His bot uses relative pixel percentages in AutoIT. It is a bit more forgiving when it comes to game screen size. I did have issues myself though when I used his bot a while ago if my screen wasn't set to the proper size/contrast ratio.

**Comment by Billty09** [comment]
unsuccessful , I tried several times.
![windows](https://user-images.githubusercontent.com/21139805/31729875-89baf7c6-b45a-11e7-9585-d55f8afd1535.jpg)
Or will it be on my screen?

**Comment by woody34** [comment]
Your screen resolution is set lower than NoxPlayer. This must be your problem. Currently I do not have support for resolutions this low. In the future I plan on adding support for pixel location percentages which will solve your problem. At this time the bot will not work for you without some re-programming unless you can run at a higher resolution.

![capture](https://user-images.githubusercontent.com/8930703/31745396-26d68436-b428-11e7-91ce-da902fa136f6.PNG)

**Comment by Billty09** [comment]
![display](https://user-images.githubusercontent.com/21139805/31772562-4ef4c4ae-b50a-11e7-8ea2-72c552d3f3f3.jpg)
My computer max resolution ,
Please support low resolution

thankyou , thaipeopleneedyou
